### ISSUE TITLE
How to get QUERY_API_KEY from a public task

### ISSUE THREAD

**Issue by TysonYu** [soco-ai/soco-core-python#3]
I find a task which is already published. The url is https://app.soco.ai/main/covid-19, How can I get the QUERY_API_KEY for this task so that I can write python scripts about this task to get result?
Like this
![image](https://user-images.githubusercontent.com/25273614/77645986-a6ab9500-6f9e-11ea-8104-fc3383dd060f.png)

**Comment by snakeztc** [comment]
The QUERY_KEY for the COVID-19 is 78f0299c-17b2-4851-83c6-06d9856de42a

**Comment by TysonYu** [comment]
Thank You. Btw, what is your data set? is it COVID-19 Open Research Dataset (CORD-19)?

**Comment by snakeztc** [comment]
Yes. It's the data set provided by the Kaggle competition. https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge
